// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Postal")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DataLayer.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SignedIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Password = "123",
                            SignedIn = false,
                            Username = "Administrator"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Rock"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Pop"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Jazz"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Classical"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Blues"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Country"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Reggae"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Hip-Hop"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Electronic"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Folk"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Models.OrderProductDetails", b =>
                {
                    b.Property<int>("OrderProductDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderProductDetailsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("OrderProductDetailsId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderProductDetails");
                });

            modelBuilder.Entity("DataLayer.Models.RecordLabel", b =>
                {
                    b.Property<int>("RecordLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordLabelId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("RecordLabelId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("RecordLabels");

                    b.HasData(
                        new
                        {
                            RecordLabelId = 1,
                            LabelName = "Label-1"
                        },
                        new
                        {
                            RecordLabelId = 2,
                            LabelName = "Label-2"
                        },
                        new
                        {
                            RecordLabelId = 3,
                            LabelName = "Label-3"
                        },
                        new
                        {
                            RecordLabelId = 4,
                            LabelName = "Label-4"
                        },
                        new
                        {
                            RecordLabelId = 5,
                            LabelName = "Label-5"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("NumStars")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<int>("VinylId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("VinylId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            NumStars = 3,
                            ReviewComment = "Review for album-1",
                            VinylId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            NumStars = 1,
                            ReviewComment = "Review for album-2",
                            VinylId = 2
                        },
                        new
                        {
                            ReviewId = 3,
                            NumStars = 4,
                            ReviewComment = "Review for album-3",
                            VinylId = 3
                        },
                        new
                        {
                            ReviewId = 4,
                            NumStars = 3,
                            ReviewComment = "Review for album-4",
                            VinylId = 4
                        },
                        new
                        {
                            ReviewId = 5,
                            NumStars = 4,
                            ReviewComment = "Review for album-5",
                            VinylId = 5
                        },
                        new
                        {
                            ReviewId = 6,
                            NumStars = 2,
                            ReviewComment = "Review for album-6",
                            VinylId = 6
                        },
                        new
                        {
                            ReviewId = 7,
                            NumStars = 4,
                            ReviewComment = "Review for album-7",
                            VinylId = 7
                        },
                        new
                        {
                            ReviewId = 8,
                            NumStars = 4,
                            ReviewComment = "Review for album-8",
                            VinylId = 8
                        },
                        new
                        {
                            ReviewId = 9,
                            NumStars = 4,
                            ReviewComment = "Review for album-9",
                            VinylId = 9
                        },
                        new
                        {
                            ReviewId = 10,
                            NumStars = 1,
                            ReviewComment = "Review for album-10",
                            VinylId = 10
                        },
                        new
                        {
                            ReviewId = 11,
                            NumStars = 2,
                            ReviewComment = "Review for album-11",
                            VinylId = 11
                        },
                        new
                        {
                            ReviewId = 12,
                            NumStars = 3,
                            ReviewComment = "Review for album-12",
                            VinylId = 12
                        },
                        new
                        {
                            ReviewId = 13,
                            NumStars = 1,
                            ReviewComment = "Review for album-13",
                            VinylId = 13
                        },
                        new
                        {
                            ReviewId = 14,
                            NumStars = 4,
                            ReviewComment = "Review for album-14",
                            VinylId = 14
                        },
                        new
                        {
                            ReviewId = 15,
                            NumStars = 4,
                            ReviewComment = "Review for album-15",
                            VinylId = 15
                        },
                        new
                        {
                            ReviewId = 16,
                            NumStars = 2,
                            ReviewComment = "Review for album-16",
                            VinylId = 16
                        },
                        new
                        {
                            ReviewId = 17,
                            NumStars = 1,
                            ReviewComment = "Review for album-17",
                            VinylId = 17
                        },
                        new
                        {
                            ReviewId = 18,
                            NumStars = 4,
                            ReviewComment = "Review for album-18",
                            VinylId = 18
                        },
                        new
                        {
                            ReviewId = 19,
                            NumStars = 1,
                            ReviewComment = "Review for album-19",
                            VinylId = 19
                        },
                        new
                        {
                            ReviewId = 20,
                            NumStars = 3,
                            ReviewComment = "Review for album-20",
                            VinylId = 20
                        },
                        new
                        {
                            ReviewId = 21,
                            NumStars = 3,
                            ReviewComment = "Review for album-21",
                            VinylId = 21
                        },
                        new
                        {
                            ReviewId = 22,
                            NumStars = 3,
                            ReviewComment = "Review for album-22",
                            VinylId = 22
                        },
                        new
                        {
                            ReviewId = 23,
                            NumStars = 4,
                            ReviewComment = "Review for album-23",
                            VinylId = 23
                        },
                        new
                        {
                            ReviewId = 24,
                            NumStars = 2,
                            ReviewComment = "Review for album-24",
                            VinylId = 24
                        },
                        new
                        {
                            ReviewId = 25,
                            NumStars = 1,
                            ReviewComment = "Review for album-25",
                            VinylId = 25
                        },
                        new
                        {
                            ReviewId = 26,
                            NumStars = 3,
                            ReviewComment = "Review for album-26",
                            VinylId = 26
                        },
                        new
                        {
                            ReviewId = 27,
                            NumStars = 2,
                            ReviewComment = "Review for album-27",
                            VinylId = 27
                        },
                        new
                        {
                            ReviewId = 28,
                            NumStars = 4,
                            ReviewComment = "Review for album-28",
                            VinylId = 28
                        },
                        new
                        {
                            ReviewId = 29,
                            NumStars = 3,
                            ReviewComment = "Review for album-29",
                            VinylId = 29
                        },
                        new
                        {
                            ReviewId = 30,
                            NumStars = 3,
                            ReviewComment = "Review for album-30",
                            VinylId = 30
                        },
                        new
                        {
                            ReviewId = 31,
                            NumStars = 1,
                            ReviewComment = "Review for album-31",
                            VinylId = 31
                        },
                        new
                        {
                            ReviewId = 32,
                            NumStars = 4,
                            ReviewComment = "Review for album-32",
                            VinylId = 32
                        },
                        new
                        {
                            ReviewId = 33,
                            NumStars = 3,
                            ReviewComment = "Review for album-33",
                            VinylId = 33
                        },
                        new
                        {
                            ReviewId = 34,
                            NumStars = 3,
                            ReviewComment = "Review for album-34",
                            VinylId = 34
                        },
                        new
                        {
                            ReviewId = 35,
                            NumStars = 1,
                            ReviewComment = "Review for album-35",
                            VinylId = 35
                        },
                        new
                        {
                            ReviewId = 36,
                            NumStars = 4,
                            ReviewComment = "Review for album-36",
                            VinylId = 36
                        },
                        new
                        {
                            ReviewId = 37,
                            NumStars = 4,
                            ReviewComment = "Review for album-37",
                            VinylId = 37
                        },
                        new
                        {
                            ReviewId = 38,
                            NumStars = 3,
                            ReviewComment = "Review for album-38",
                            VinylId = 38
                        },
                        new
                        {
                            ReviewId = 39,
                            NumStars = 3,
                            ReviewComment = "Review for album-39",
                            VinylId = 39
                        },
                        new
                        {
                            ReviewId = 40,
                            NumStars = 3,
                            ReviewComment = "Review for album-40",
                            VinylId = 40
                        },
                        new
                        {
                            ReviewId = 41,
                            NumStars = 1,
                            ReviewComment = "Review for album-41",
                            VinylId = 41
                        },
                        new
                        {
                            ReviewId = 42,
                            NumStars = 4,
                            ReviewComment = "Review for album-42",
                            VinylId = 42
                        },
                        new
                        {
                            ReviewId = 43,
                            NumStars = 1,
                            ReviewComment = "Review for album-43",
                            VinylId = 43
                        },
                        new
                        {
                            ReviewId = 44,
                            NumStars = 1,
                            ReviewComment = "Review for album-44",
                            VinylId = 44
                        },
                        new
                        {
                            ReviewId = 45,
                            NumStars = 4,
                            ReviewComment = "Review for album-45",
                            VinylId = 45
                        },
                        new
                        {
                            ReviewId = 46,
                            NumStars = 3,
                            ReviewComment = "Review for album-46",
                            VinylId = 46
                        },
                        new
                        {
                            ReviewId = 47,
                            NumStars = 1,
                            ReviewComment = "Review for album-47",
                            VinylId = 47
                        },
                        new
                        {
                            ReviewId = 48,
                            NumStars = 2,
                            ReviewComment = "Review for album-48",
                            VinylId = 48
                        },
                        new
                        {
                            ReviewId = 49,
                            NumStars = 3,
                            ReviewComment = "Review for album-49",
                            VinylId = 49
                        },
                        new
                        {
                            ReviewId = 50,
                            NumStars = 3,
                            ReviewComment = "Review for album-50",
                            VinylId = 50
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Vinyl", b =>
                {
                    b.Property<int>("VinylId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VinylId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("RecordLabelId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VinylId");

                    b.HasIndex("RecordLabelId");

                    b.ToTable("Vinyls");

                    b.HasData(
                        new
                        {
                            VinylId = 1,
                            Price = 20.140000000000001,
                            RecordLabelId = 1,
                            Title = "Album-1"
                        },
                        new
                        {
                            VinylId = 2,
                            Price = 31.350000000000001,
                            RecordLabelId = 1,
                            Title = "Album-2"
                        },
                        new
                        {
                            VinylId = 3,
                            Price = 17.960000000000001,
                            RecordLabelId = 1,
                            Title = "Album-3"
                        },
                        new
                        {
                            VinylId = 4,
                            Price = 47.07,
                            RecordLabelId = 3,
                            Title = "Album-4"
                        },
                        new
                        {
                            VinylId = 5,
                            Price = 25.809999999999999,
                            RecordLabelId = 4,
                            Title = "Album-5"
                        },
                        new
                        {
                            VinylId = 6,
                            Price = 21.359999999999999,
                            RecordLabelId = 1,
                            Title = "Album-6"
                        },
                        new
                        {
                            VinylId = 7,
                            Price = 19.57,
                            RecordLabelId = 3,
                            Title = "Album-7"
                        },
                        new
                        {
                            VinylId = 8,
                            Price = 36.450000000000003,
                            RecordLabelId = 1,
                            Title = "Album-8"
                        },
                        new
                        {
                            VinylId = 9,
                            Price = 13.44,
                            RecordLabelId = 4,
                            Title = "Album-9"
                        },
                        new
                        {
                            VinylId = 10,
                            Price = 38.200000000000003,
                            RecordLabelId = 3,
                            Title = "Album-10"
                        },
                        new
                        {
                            VinylId = 11,
                            Price = 49.149999999999999,
                            RecordLabelId = 3,
                            Title = "Album-11"
                        },
                        new
                        {
                            VinylId = 12,
                            Price = 29.969999999999999,
                            RecordLabelId = 4,
                            Title = "Album-12"
                        },
                        new
                        {
                            VinylId = 13,
                            Price = 39.259999999999998,
                            RecordLabelId = 2,
                            Title = "Album-13"
                        },
                        new
                        {
                            VinylId = 14,
                            Price = 21.190000000000001,
                            RecordLabelId = 3,
                            Title = "Album-14"
                        },
                        new
                        {
                            VinylId = 15,
                            Price = 13.75,
                            RecordLabelId = 2,
                            Title = "Album-15"
                        },
                        new
                        {
                            VinylId = 16,
                            Price = 24.920000000000002,
                            RecordLabelId = 4,
                            Title = "Album-16"
                        },
                        new
                        {
                            VinylId = 17,
                            Price = 20.539999999999999,
                            RecordLabelId = 2,
                            Title = "Album-17"
                        },
                        new
                        {
                            VinylId = 18,
                            Price = 41.100000000000001,
                            RecordLabelId = 3,
                            Title = "Album-18"
                        },
                        new
                        {
                            VinylId = 19,
                            Price = 43.600000000000001,
                            RecordLabelId = 2,
                            Title = "Album-19"
                        },
                        new
                        {
                            VinylId = 20,
                            Price = 40.219999999999999,
                            RecordLabelId = 2,
                            Title = "Album-20"
                        },
                        new
                        {
                            VinylId = 21,
                            Price = 19.25,
                            RecordLabelId = 3,
                            Title = "Album-21"
                        },
                        new
                        {
                            VinylId = 22,
                            Price = 25.940000000000001,
                            RecordLabelId = 4,
                            Title = "Album-22"
                        },
                        new
                        {
                            VinylId = 23,
                            Price = 49.490000000000002,
                            RecordLabelId = 1,
                            Title = "Album-23"
                        },
                        new
                        {
                            VinylId = 24,
                            Price = 44.210000000000001,
                            RecordLabelId = 1,
                            Title = "Album-24"
                        },
                        new
                        {
                            VinylId = 25,
                            Price = 39.840000000000003,
                            RecordLabelId = 1,
                            Title = "Album-25"
                        },
                        new
                        {
                            VinylId = 26,
                            Price = 20.449999999999999,
                            RecordLabelId = 4,
                            Title = "Album-26"
                        },
                        new
                        {
                            VinylId = 27,
                            Price = 48.719999999999999,
                            RecordLabelId = 2,
                            Title = "Album-27"
                        },
                        new
                        {
                            VinylId = 28,
                            Price = 49.600000000000001,
                            RecordLabelId = 4,
                            Title = "Album-28"
                        },
                        new
                        {
                            VinylId = 29,
                            Price = 30.280000000000001,
                            RecordLabelId = 2,
                            Title = "Album-29"
                        },
                        new
                        {
                            VinylId = 30,
                            Price = 48.560000000000002,
                            RecordLabelId = 3,
                            Title = "Album-30"
                        },
                        new
                        {
                            VinylId = 31,
                            Price = 15.08,
                            RecordLabelId = 2,
                            Title = "Album-31"
                        },
                        new
                        {
                            VinylId = 32,
                            Price = 16.440000000000001,
                            RecordLabelId = 1,
                            Title = "Album-32"
                        },
                        new
                        {
                            VinylId = 33,
                            Price = 23.059999999999999,
                            RecordLabelId = 1,
                            Title = "Album-33"
                        },
                        new
                        {
                            VinylId = 34,
                            Price = 27.98,
                            RecordLabelId = 2,
                            Title = "Album-34"
                        },
                        new
                        {
                            VinylId = 35,
                            Price = 41.25,
                            RecordLabelId = 1,
                            Title = "Album-35"
                        },
                        new
                        {
                            VinylId = 36,
                            Price = 14.210000000000001,
                            RecordLabelId = 2,
                            Title = "Album-36"
                        },
                        new
                        {
                            VinylId = 37,
                            Price = 25.460000000000001,
                            RecordLabelId = 1,
                            Title = "Album-37"
                        },
                        new
                        {
                            VinylId = 38,
                            Price = 11.130000000000001,
                            RecordLabelId = 2,
                            Title = "Album-38"
                        },
                        new
                        {
                            VinylId = 39,
                            Price = 17.77,
                            RecordLabelId = 4,
                            Title = "Album-39"
                        },
                        new
                        {
                            VinylId = 40,
                            Price = 21.370000000000001,
                            RecordLabelId = 1,
                            Title = "Album-40"
                        },
                        new
                        {
                            VinylId = 41,
                            Price = 27.199999999999999,
                            RecordLabelId = 2,
                            Title = "Album-41"
                        },
                        new
                        {
                            VinylId = 42,
                            Price = 37.07,
                            RecordLabelId = 2,
                            Title = "Album-42"
                        },
                        new
                        {
                            VinylId = 43,
                            Price = 36.289999999999999,
                            RecordLabelId = 1,
                            Title = "Album-43"
                        },
                        new
                        {
                            VinylId = 44,
                            Price = 14.529999999999999,
                            RecordLabelId = 4,
                            Title = "Album-44"
                        },
                        new
                        {
                            VinylId = 45,
                            Price = 14.720000000000001,
                            RecordLabelId = 3,
                            Title = "Album-45"
                        },
                        new
                        {
                            VinylId = 46,
                            Price = 47.719999999999999,
                            RecordLabelId = 3,
                            Title = "Album-46"
                        },
                        new
                        {
                            VinylId = 47,
                            Price = 20.969999999999999,
                            RecordLabelId = 4,
                            Title = "Album-47"
                        },
                        new
                        {
                            VinylId = 48,
                            Price = 25.449999999999999,
                            RecordLabelId = 3,
                            Title = "Album-48"
                        },
                        new
                        {
                            VinylId = 49,
                            Price = 43.439999999999998,
                            RecordLabelId = 4,
                            Title = "Album-49"
                        },
                        new
                        {
                            VinylId = 50,
                            Price = 20.489999999999998,
                            RecordLabelId = 4,
                            Title = "Album-50"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.VinylCover", b =>
                {
                    b.Property<int>("VinylCoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VinylCoverId"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VinylId")
                        .HasColumnType("integer");

                    b.HasKey("VinylCoverId");

                    b.HasIndex("VinylId");

                    b.ToTable("Covers");
                });

            modelBuilder.Entity("DataLayer.Models.VinylGenre", b =>
                {
                    b.Property<int>("VinylId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("VinylId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("vinylGenres");

                    b.HasData(
                        new
                        {
                            VinylId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            VinylId = 2,
                            GenreId = 6
                        },
                        new
                        {
                            VinylId = 3,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            VinylId = 5,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 6,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 7,
                            GenreId = 8
                        },
                        new
                        {
                            VinylId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 10,
                            GenreId = 4
                        },
                        new
                        {
                            VinylId = 11,
                            GenreId = 3
                        },
                        new
                        {
                            VinylId = 12,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 13,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 14,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 15,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 16,
                            GenreId = 3
                        },
                        new
                        {
                            VinylId = 17,
                            GenreId = 4
                        },
                        new
                        {
                            VinylId = 18,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 19,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 21,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 22,
                            GenreId = 4
                        },
                        new
                        {
                            VinylId = 23,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 24,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 25,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 26,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 27,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 28,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 29,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 30,
                            GenreId = 6
                        },
                        new
                        {
                            VinylId = 31,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 32,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 34,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 35,
                            GenreId = 2
                        },
                        new
                        {
                            VinylId = 36,
                            GenreId = 4
                        },
                        new
                        {
                            VinylId = 37,
                            GenreId = 8
                        },
                        new
                        {
                            VinylId = 38,
                            GenreId = 6
                        },
                        new
                        {
                            VinylId = 39,
                            GenreId = 6
                        },
                        new
                        {
                            VinylId = 40,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 41,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 42,
                            GenreId = 8
                        },
                        new
                        {
                            VinylId = 43,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 44,
                            GenreId = 5
                        },
                        new
                        {
                            VinylId = 45,
                            GenreId = 3
                        },
                        new
                        {
                            VinylId = 46,
                            GenreId = 1
                        },
                        new
                        {
                            VinylId = 47,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 48,
                            GenreId = 9
                        },
                        new
                        {
                            VinylId = 49,
                            GenreId = 7
                        },
                        new
                        {
                            VinylId = 50,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("DataLayer.Models.OrderProductDetails", b =>
                {
                    b.HasOne("DataLayer.Models.Order", "Order")
                        .WithMany("OrderProductDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataLayer.Models.RecordLabel", b =>
                {
                    b.HasOne("DataLayer.Models.Address", "Address")
                        .WithOne("RecordLabel")
                        .HasForeignKey("DataLayer.Models.RecordLabel", "AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DataLayer.Models.Review", b =>
                {
                    b.HasOne("DataLayer.Models.Vinyl", "Vinyl")
                        .WithMany("Reviews")
                        .HasForeignKey("VinylId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vinyl");
                });

            modelBuilder.Entity("DataLayer.Models.Vinyl", b =>
                {
                    b.HasOne("DataLayer.Models.RecordLabel", "RecordLabel")
                        .WithMany("Vinyls")
                        .HasForeignKey("RecordLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordLabel");
                });

            modelBuilder.Entity("DataLayer.Models.VinylCover", b =>
                {
                    b.HasOne("DataLayer.Models.Vinyl", "Vinyl")
                        .WithMany("Covers")
                        .HasForeignKey("VinylId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vinyl");
                });

            modelBuilder.Entity("DataLayer.Models.VinylGenre", b =>
                {
                    b.HasOne("DataLayer.Models.Genre", "Genre")
                        .WithMany("Vinyls")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Vinyl", "Vinyl")
                        .WithMany("Genres")
                        .HasForeignKey("VinylId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Vinyl");
                });

            modelBuilder.Entity("DataLayer.Models.Address", b =>
                {
                    b.Navigation("RecordLabel")
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Models.Genre", b =>
                {
                    b.Navigation("Vinyls");
                });

            modelBuilder.Entity("DataLayer.Models.Order", b =>
                {
                    b.Navigation("OrderProductDetails");
                });

            modelBuilder.Entity("DataLayer.Models.RecordLabel", b =>
                {
                    b.Navigation("Vinyls");
                });

            modelBuilder.Entity("DataLayer.Models.Vinyl", b =>
                {
                    b.Navigation("Covers");

                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
